### ISSUE TITLE
Long route computing time

### ISSUE THREAD

**Issue by Utyff** [Utyff/pMetro#1]
Расчет маршрута и времени может длится очень долго на сложных схемах (до 3 минут по Нью-Йорку)

**Comment by asdzxcasd** [comment]
Я переписал вычисление кратчайшего маршрута. До этого по Нью-Йорку у меня считался тоже несколько минут, а сейчас получается порядка 100мс. Результат совпадает с тем, что выдаёт pMetro под Windows.
Ещё я добавил вычисление альтернативных маршрутов, но пока без интерфейса.
Если не возражаете, немного подчищу код и выложу сюда то, что получилось.

**Comment by Utyff** [comment]
Это здорово! Решение красивое. Я бы долго переписывал :)
Добавляй свой код. Я добавлю тебя в About и сделаю релиз.

**Comment by asdzxcasd** [comment]
Хорошо! Я ещё хочу исправить пару ошибок и немного потестировать, и тогда добавлю.

**Comment by asdzxcasd** [comment]
Наверное уже можно закрыть этот issue.
