### ISSUE TITLE
Устаревший каталог карт

### ISSUE THREAD

**Issue by asdzxcasd** [Utyff/pMetro#10]
Каталог на сайте pMetro (http://pmetro.su/Files.xml) не обновлялся с 13 марта 2016 г. (день номер 42442), хотя некоторые схемы обновились, например, схема Москвы. Из-за этого в приложении карты не обновляются автоматически. Возможно ли связаться с Борисом, чтобы попросить обновить каталог?

**Comment by Utyff** [comment]
Написать Борису можно. Адрес Boris[]pMetro.su. Отвечает он не всегда. Лучше сделать новый файл и отправить ему. Это повысит шансы :)

**Comment by asdzxcasd** [comment]
Спасибо, как раз из-за того, что он не отвечает, и спрашиваю. Попробую обновить Files.xml, но пока не понятно, откуда брать даты изменения схем. Такое ощущение, что этот файл генерируется программно.

**Comment by Utyff** [comment]
Я не совсем понял вопрос.
Дата в Files.xml в формате Дельфи. Конвертируется так:
======
 long date = 42442;
 long javaTime = (date - 25569L) * 86400L * 1000L;
 String str = DateFormat.getDateInstance(DateFormat.MEDIUM).format(new java.util.Date(javaTime));
======
Борис наверняка делает это какой-то программой и забыл ее запустить.
Я попробую написать на форуме pmetro. Может там прочтет.

**Comment by Utyff** [comment]
Я не совсем понял вопрос.

Дата в Files.xml в формате Дельфи. Конвертируется так:

long date = 42442;
long javaTime = (date - 25569L) \* 86400L \* 1000L;
String str = DateFormat.getDateInstance(DateFormat.MEDIUM).format(new java.util.Date(javaTime));

Борис наверняка делает это какой-то программой и забыл ее запустить.
Я попробую написать на форуме pmetro. Может там прочтет.

**Comment by asdzxcasd** [comment]
Про даты изменения схем я имел в виду, что не знал, где найти эти даты на сайте. Но, как оказалось, их можно найти просто на страницах скачивания схем.

**Comment by Utyff** [comment]
Я думаю можно просто взять дату изменения PMZ файла. Эта дата сохраняется внутри ZIP архива и не меняется.

**Comment by asdzxcasd** [comment]
Сделал новый Files.xml Скрипт для его генерации: https://gist.github.com/asdzxcasd/81f561915536ba80f0718dc666e5dd37
[Files.zip](https://github.com/Utyff/pMetro/files/496131/Files.zip)

**Comment by Utyff** [comment]
Это отлично.
Борис дал "добро" на то чтобы выложить карты на Github.
Нужно придумать как их хранить и запаковывать в PMZ потом в ZIP.
Я думаю сделать для Windiws CMD-скрипт и для Linux SH-скрипт.
Скрипты не требуют доп. софта и с питоном я не работал :)

**Comment by Utyff** [comment]
Я отправил Борису письмо с файлом. Ждем..

**Comment by Utyff** [comment]
Борис обновил каталог.
Сказал спасибо за файл :)

**Comment by asdzxcasd** [comment]
О, отлично!
А насчёт того, чтобы выложить на GitHub - это про файлы, которые лежат внутри PMZ? Или только уже запакованные в PMZ и ZIP?

**Comment by Utyff** [comment]
Можно сделать как угодно.
Чтобы отслеживать изменения файлов нужно хранить карты распакованными.
Есть одна трудность - файл Readme.txt внутри некоторых .ZIP, но не .PMZ

Я выложил распакованные карты:
https://github.com/Utyff/pMetro-maps
