### ISSUE TITLE
Варианты маршрутов

### ISSUE THREAD

**Issue by dimqua** [Utyff/pMetro#18]
Не хватает возможности отображения всех возможных маршрутов (а не только наиболее быстрого).

**Comment by asdzxcasd** [comment]
Я пробовал реализовать альтернативные маршруты, но пока делал, поломал некоторые вещи, в основном связанные с интерфейсом, которые так и не исправил. Маршруты прокладываются нормально, хотя и отличаются от тех, что показывает pMetro. В этот репозиторий изменения пока не выкладывал. Если это интересно, попробую довести до ума.

**Comment by dimqua** [comment]
Я только потом прочитал на 4pda, что эта возможность запланирована автором. :-)

А что значит "отличаются от тех, что показывает pMetro"? Если от станции метро А до станции Б можно доехать, предположим, тремя способами и больше никак, то как маршруты могут отличаться в разных программах?

**Comment by Utyff** [comment]
It not an issue.
