### ISSUE TITLE
Можно добавить поиск станций по названию?

### ISSUE THREAD

**Issue by SoNickRND** [Utyff/pMetro#23]
Можно добавить поиск станций по названию?
Или я не понял как пользоваться схемой. Залил Москву и понял что искать маршрут можно только тыкая по карте пальцем.

**Comment by Utyff** [comment]
Я не планирую заниматься pMetro. Если есть жедание - сам можешь сделать.

**Comment by OmlineEditor** [comment]
А тикет зачем закрывать? оставьте его открытым может кто-то добавит поиск
