### ISSUE TITLE
Upgrade license to GPLv2+

### ISSUE THREAD

**Issue by ghost** [Utyff/pMetro#3]
You use Android support libraries which are Apache2 licensed. Apache2 license is considered incompatible with plain GPLv2. Explicitly stating that GPLv2 is meant to include the "and any later version" statement would resolve this issue.

**Comment by Utyff** [comment]
I've changed the license to GPL v3+.
Will it solve the incompatibility with Android support libraries?

**Comment by ghost** [comment]
Yes, indeed it does :)
