### ISSUE TITLE
Active transportations are resetted when schemes are switched

### ISSUE THREAD

**Issue by asdzxcasd** [Utyff/pMetro#6]
It is inconvenient to find route that stretches across several transportations. One has to manually adjust allowed transportations in menu.

I suggest that in the case start station is selected, previous transportation doesn't become inactive when schemes are switched. E.g. if start station is selected in metro, then scheme is changed to display rail and end rail station is selected. It would be logical if both metro and rail are available, so the route goes from metro to rail.

**Comment by Utyff** [comment]
You're right.
I did it on purpose, because route calculation was a slow when all schemes enabled.
Now it can be removed.

**Comment by Utyff** [comment]
I removed MAP parameter CheckedTransport that used for disable Transports.
Now route will not change when maps are switched.
